name: busfinder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  busfinder_api:
    path: packages/busfinder_api
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  bloc: ^9.1.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  provider: ^6.1.5+1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  vector_map_tiles: ^9.0.0-beta.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/background.jpg
